//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWordPress.PageObjects {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class profilepageObject {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal profilepageObject() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestWordPress.PageObjects.profilepageObject", typeof(profilepageObject).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;description&apos;].
        /// </summary>
        internal static string AboutmeText {
            get {
                return ResourceManager.GetString("AboutmeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;first_name&apos;].
        /// </summary>
        internal static string FirstNameText {
            get {
                return ResourceManager.GetString("FirstNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;last_name&apos;].
        /// </summary>
        internal static string LastNameText {
            get {
                return ResourceManager.GetString("LastNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //li[contains(@class,&apos;profile&apos;)]/a.
        /// </summary>
        internal static string MyProfileTab {
            get {
                return ResourceManager.GetString("MyProfileTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;password&apos;].
        /// </summary>
        internal static string NewPasswordText {
            get {
                return ResourceManager.GetString("NewPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //span[contains(.,&apos;Your password can be saved&apos;)].
        /// </summary>
        internal static string PasswordCanSaveMessage {
            get {
                return ResourceManager.GetString("PasswordCanSaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //button[contains(@type,&apos;submit&apos;)].
        /// </summary>
        internal static string Savebutton {
            get {
                return ResourceManager.GetString("Savebutton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[contains(@class,&apos;is-success&apos;)].
        /// </summary>
        internal static string SaveSuccessMessage {
            get {
                return ResourceManager.GetString("SaveSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //li[@class=&apos;security&apos;]/a.
        /// </summary>
        internal static string SecurityTab {
            get {
                return ResourceManager.GetString("SecurityTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //button[contains(.,&apos;Sign Out&apos;)].
        /// </summary>
        internal static string SignOutbutton {
            get {
                return ResourceManager.GetString("SignOutbutton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //h2[@class=&apos;profile-gravatar__user-display-name&apos;].
        /// </summary>
        internal static string usernamedisplay {
            get {
                return ResourceManager.GetString("usernamedisplay", resourceCulture);
            }
        }
    }
}
